name: Webbl

services:
  # ASP.NET Webbl Api
  api:
    build:
      context: .
      dockerfile: ./tools/containers/api.Containerfile
      target: development
      args:
        - API_DIR=./server/Api
        - HTTP_PORT=5000
        - HTTPS_PORT=5001
    container_name: webbl-api-dev
    restart: unless-stopped
    ports:
      - "${API_HTTP_PORT:-5000}:5000"
      - "${API_HTTPS_PORT:-5001}:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=myapp_dev;Username=devuser;Password=devpassword
    volumes:
      - ./server/Api:/app
      - /app/obj
      - /app/bin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - web-api-network
      - api-db-network

  # Angular Webbl Frontend
  web:
    build:
      context: .
      dockerfile: ./tools/containers/web.Containerfile
      target: development
      args:
        - WEB_DIR=./web
        - NGINX_CONF=./tools/config/nginx.conf
    container_name: webbl-web-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:${HTTP_PORT:-5000}
    volumes:
      - ./web/src/:/app/src
      - ./web/angular.json:/app/angular.json
      - ./web/tsconfig.json:/app/tsconfig.json
      - ./web/tsconfig.app.json:/app/tsconfig.app.json
      - /app/nodemodules
    depends_on:
      - api
    networks:
      - web-api-network

  # Webbl Database
  postgres:
    image: postgres:16-alpine
    container_name: webbl-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-webbl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-webbl}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./tools/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api-db-network

volumes:
  postgres-data:
    driver: local

networks:
  web-api-network:
    driver: bridge
  api-db-network:
    driver: bridge
