name: Webbl

services:
  frontend:
    build:
      context: ./web/
    networks:
      - frontend
    ports: 
      - 8080:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./server/Api
    networks:
      - frontend

networks:
  frontend:
